name = "web3ns"
main = "src/index.ts"
compatibility_date = "2023-02-07"
vars = { ENVIRONMENT = "prd" }

kv_namespaces = [
    { binding = "names",     id = "e0e1c2d8395e488982ef865c5b36cbb0", preview_id = "f5574baa8d4c47afbea81b27b045bfd9" },
    { binding = "addresses", id = "2b214521bc604c03a1e467e84e78dafc", preview_id = "0f1e086eab7142a1a35dd30979c0a4ca" }
]

[env.staging]
vars = { ENVIRONMENT = "stg" }
workers_dev = true

kv_namespaces = [
    { binding = "names",     id = "cde5aff1cf884e86921ba5dea091b099", preview_id = "f5574baa8d4c47afbea81b27b045bfd9" },
    { binding = "addresses", id = "6d683d2c22b54d22a0da2b92ac1b2c02", preview_id = "0f1e086eab7142a1a35dd30979c0a4ca" },
    { binding = "ensDb",     id = "99fb559b588c491aa91e81416839f78c", preview_id = "155b3702234c4897a62bc87f0e3efaf9" }
]
