name = "web3ns"
main = "src/index.ts"
compatibility_date = "2023-02-07"
kv_namespaces = [
    { binding = "names", id = "e0e1c2d8395e488982ef865c5b36cbb0", preview_id = "f5574baa8d4c47afbea81b27b045bfd9" }
]